# Generated by Django 5.1.7 on 2025-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
